workflows:
  ios-workflow:
    name: Smart Payroll iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_PROJECT: "Smart_payroll.xcodeproj"
        XCODE_SCHEME: "Smart payroll"
        BUNDLE_ID: "ch.taxley.smartpayroll"
        DEVELOPMENT_TEAM: "zürich financial solutions GmbH"
      xcode: latest
    scripts:
      - name: Build and Archive iOS app
        script: |
          # Build archive with automatic provisioning updates
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -destination 'generic/platform=iOS' \
            -archivePath "build/Smart_payroll.xcarchive" \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM="zürich financial solutions GmbH" \
            CODE_SIGN_IDENTITY="Apple Development"
          
          # Export IPA
          xcodebuild -exportArchive \
            -archivePath "build/Smart_payroll.xcarchive" \
            -exportPath "build/ios/ipa" \
            -exportOptionsPlist "export_options.plist"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/Smart_payroll.xcarchive
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - hacibozca@gmail.com
        notify:
          success: true
          failure: true 