workflows:
  ios-workflow:
    name: Smart Payroll iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_PROJECT: "Smart_payroll.xcodeproj"
        XCODE_SCHEME: "Smart payroll"
        BUNDLE_ID: "ch.taxley.smartpayroll"
      xcode: latest
    scripts:
      - name: Build iOS app
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --export-method "development"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - hacibozca@gmail.com
        notify:
          success: true
          failure: true 