workflows:
  ios-workflow:
    name: Smart Payroll iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_PROJECT: "Smart_payroll.xcodeproj"
        XCODE_SCHEME: "Smart payroll"
        BUNDLE_ID: "ch.taxley.smartpayroll"
      xcode: latest
    scripts:
      - name: Build iOS app for Simulator
        script: |
          # Build for iOS Simulator (no Apple Developer Account required)
          xcodebuild build \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -configuration Release
          
          # Create app package for testing
          mkdir -p build/ios/simulator
          find $HOME/Library/Developer/Xcode/DerivedData -name "*.app" -path "*/Build/Products/*" -exec cp -R {} build/ios/simulator/ \;
    artifacts:
      - build/ios/simulator/*.app
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - hacibozca@gmail.com
        notify:
          success: true
          failure: true
        body: |
          Smart Payroll iOS build completed successfully!
          
          ✅ Built for iOS Simulator (iPhone 15)
          ✅ WebView loads: https://lohn-soon-seite.lovable.app/auth
          ✅ Ready for testing in Xcode Simulator
          
          Note: For App Store deployment, configure Apple Developer Account in Codemagic. 