workflows:
  ios-workflow:
    name: Smart Payroll iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: ch.taxley.smartpayroll
      vars:
        XCODE_PROJECT: "Smart_payroll.xcodeproj"
        XCODE_SCHEME: "Smart payroll"
        BUNDLE_ID: "ch.taxley.smartpayroll"
      xcode: latest
    scripts:
      - name: Set up keychain to be used for codesigning
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID \
            --type IOS_APP_DEVELOPMENT \
            --create
      - name: Add certificates to keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Build and Archive iOS app
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - hacibozca@gmail.com
        notify:
          success: true
          failure: true 